import { TranscriptSegment, CaptionTrack } from "./types";

export function extractVideoId(url: string): string | null {
  const trimmed = url.trim();

  const patterns = [
    /(?:youtube\.com\/watch\?.*v=)([a-zA-Z0-9_-]{11})/,
    /(?:youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/v\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/live\/)([a-zA-Z0-9_-]{11})/,
  ];

  for (const pattern of patterns) {
    const match = trimmed.match(pattern);
    if (match) return match[1];
  }

  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) return trimmed;

  return null;
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&#x2F;/g, "/")
    .replace(/&nbsp;/g, " ")
    .replace(/\n/g, " ")
    .trim();
}

function parseTranscriptXml(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  // YouTube caption XML: <text start="1.52" dur="3.36">caption text</text>
  const regex =
    /<text\s+start="([\d.]+)"\s+dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;

  for (const match of xml.matchAll(regex)) {
    const text = decodeHtmlEntities(match[3].replace(/<[^>]+>/g, ""));
    if (text.length > 0) {
      segments.push({
        start: parseFloat(match[1]),
        duration: parseFloat(match[2]),
        text,
      });
    }
  }

  return segments;
}

function extractPlayerResponse(html: string): Record<string, unknown> | null {
  // YouTube embeds player config in varying JS variable patterns across page versions
  const patterns = [
    /var\s+ytInitialPlayerResponse\s*=\s*({.+?})\s*;\s*var\s/,
    /ytInitialPlayerResponse\s*=\s*({.+?})\s*;\s*var\s/,
    /var\s+ytInitialPlayerResponse\s*=\s*({.+?})\s*;/,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match) {
      try {
        return JSON.parse(match[1]);
      } catch {
        continue;
      }
    }
  }

  return null;
}

export async function fetchTranscript(
  videoId: string,
  lang?: string
): Promise<{
  segments: TranscriptSegment[];
  tracks: CaptionTrack[];
  selectedTrack: CaptionTrack;
  title: string;
}> {
  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const response = await fetch(pageUrl, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept-Language": "en-US,en;q=0.9,ko;q=0.8",
      Accept:
        "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      Cookie: "CONSENT=PENDING+999; SOCS=CAESEwgDEgk2ODE4MTAyNjQaAmVuIAEaBgiA_LyaBg",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch YouTube page (status ${response.status})`);
  }

  const html = await response.text();

  const playerResponse = extractPlayerResponse(html);
  if (!playerResponse) {
    throw new Error(
      "Could not extract video data. The video might be private, unavailable, or region-locked."
    );
  }

  const videoDetails = playerResponse.videoDetails as
    | Record<string, unknown>
    | undefined;
  const title = (videoDetails?.title as string) || "Unknown";

  const captions = playerResponse.captions as Record<string, unknown> | undefined;
  const captionRenderer = captions?.playerCaptionsTracklistRenderer as
    | Record<string, unknown>
    | undefined;
  const captionTracks = captionRenderer?.captionTracks as
    | Array<Record<string, unknown>>
    | undefined;

  if (!captionTracks?.length) {
    throw new Error(
      "No captions available for this video. The creator has not enabled captions."
    );
  }

  const tracks: CaptionTrack[] = captionTracks.map((t) => {
    const name = t.name as Record<string, unknown> | undefined;
    const nameText =
      (name?.simpleText as string) ||
      ((name?.runs as Array<Record<string, unknown>>)?.[0]?.text as string) ||
      (t.languageCode as string);

    return {
      languageCode: t.languageCode as string,
      languageName: nameText,
      isAutoGenerated: t.kind === "asr",
    };
  });

  const selectedTrack = lang
    ? tracks.find((t) => t.languageCode === lang) || tracks[0]
    : tracks[0];

  const rawTrack = captionTracks.find(
    (t) => (t.languageCode as string) === selectedTrack.languageCode
  );

  if (!rawTrack?.baseUrl) {
    throw new Error("Could not find caption URL for the selected language.");
  }

  const captionResponse = await fetch(rawTrack.baseUrl as string);
  if (!captionResponse.ok) {
    throw new Error("Failed to fetch caption data from YouTube.");
  }

  const xml = await captionResponse.text();
  const segments = parseTranscriptXml(xml);

  if (segments.length === 0) {
    throw new Error("Caption data was empty or could not be parsed.");
  }

  return { segments, tracks, selectedTrack, title };
}
