"use client";

import { TranscriptSegment, CaptionTrack } from "@/lib/types";
import { toSRT, toVTT, toPlainText } from "@/lib/subtitle";

interface DownloadPanelProps {
  segments: TranscriptSegment[];
  videoId: string;
  availableTracks: CaptionTrack[];
  selectedTrack: CaptionTrack;
  onLanguageChange: (lang: string) => void;
  isEnhanced?: boolean;
}

function downloadFile(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export default function DownloadPanel({
  segments,
  videoId,
  availableTracks,
  selectedTrack,
  onLanguageChange,
  isEnhanced = false,
}: DownloadPanelProps) {
  const handleDownload = (format: "srt" | "vtt" | "txt") => {
    const generators = { srt: toSRT, vtt: toVTT, txt: toPlainText };
    const content = generators[format](segments);
    const suffix = isEnhanced ? "_sdh" : "";
    downloadFile(content, `${videoId}_${selectedTrack.languageCode}${suffix}.${format}`);
  };

  return (
    <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 p-4 bg-gray-900/50 rounded-xl border border-gray-800">
      {availableTracks.length > 1 && (
        <div className="flex items-center gap-2">
          <label htmlFor="lang-select" className="text-sm text-gray-400 whitespace-nowrap">
            Language
          </label>
          <select
            id="lang-select"
            value={selectedTrack.languageCode}
            onChange={(e) => onLanguageChange(e.target.value)}
            className="bg-gray-800 text-white text-sm rounded-lg px-3 py-2 border border-gray-700 focus:border-yellow-400 focus:outline-none"
          >
            {availableTracks.map((track) => (
              <option key={`${track.languageCode}-${track.isAutoGenerated}`} value={track.languageCode}>
                {track.languageName}
                {track.isAutoGenerated ? " (auto)" : ""}
              </option>
            ))}
          </select>
        </div>
      )}

      <div className="flex gap-2 flex-wrap">
        <button
          type="button"
          onClick={() => handleDownload("srt")}
          className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-medium rounded-lg transition-colors"
        >
          SRT Download
        </button>
        <button
          type="button"
          onClick={() => handleDownload("vtt")}
          className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium rounded-lg transition-colors"
        >
          VTT Download
        </button>
        <button
          type="button"
          onClick={() => handleDownload("txt")}
          className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white text-sm font-medium rounded-lg transition-colors"
        >
          TXT Download
        </button>
      </div>

      <span className="text-xs text-gray-500 ml-auto">
        {segments.length} segments
        {isEnhanced ? " (SDH enhanced)" : selectedTrack.isAutoGenerated ? " (auto-generated)" : " (manual)"}
      </span>
    </div>
  );
}
