import sys
import json
from youtube_transcript_api import YouTubeTranscriptApi

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"error": "Video ID required"}))
        sys.exit(1)

    video_id = sys.argv[1]
    lang = sys.argv[2] if len(sys.argv) > 2 else None

    try:
        ytt_api = YouTubeTranscriptApi()
        transcript_list = ytt_api.list(video_id)

        tracks = []
        for t in transcript_list:
            tracks.append({
                "languageCode": t.language_code,
                "languageName": t.language,
                "isAutoGenerated": t.is_generated,
            })

        preferred_langs = ["en", "ko", "ja", "es", "fr", "de", "pt", "zh-Hans"]

        if lang:
            target = transcript_list.find_transcript([lang])
        else:
            try:
                target = transcript_list.find_manually_created_transcript(preferred_langs)
            except Exception:
                try:
                    target = transcript_list.find_generated_transcript(preferred_langs)
                except Exception:
                    try:
                        target = transcript_list.find_manually_created_transcript(
                            [t.language_code for t in transcript_list]
                        )
                    except Exception:
                        target = transcript_list.find_generated_transcript(
                            [t.language_code for t in transcript_list]
                        )

        selected_track = {
            "languageCode": target.language_code,
            "languageName": target.language,
            "isAutoGenerated": target.is_generated,
        }

        segments = []
        for entry in target.fetch():
            segments.append({
                "text": entry.text,
                "start": entry.start,
                "duration": entry.duration,
            })

        print(json.dumps({
            "segments": segments,
            "availableTracks": tracks,
            "selectedTrack": selected_track,
        }))

    except Exception as e:
        print(json.dumps({"error": str(e)}))
        sys.exit(1)

if __name__ == "__main__":
    main()
